XXXXXX
  XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXXX

  XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXX XX XXX XXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XX
            BBBBBBBBBB
          XXXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXBBBBB BBBBBBBBBBBBBBBBBBBXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBXX
              
              BBBBBBBBBB
              BB BBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
              BBBBB
            XXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          BBBBB BBBBB
          BBBBBBBB
        XXXXXX
      XXXXXX
  
      XXXXXX
XXXXXXX