BBBBBBB BBBBBBBBBBB

BBBBB BBBBBBBBBBBXXXX XXXXX XXXXBBBBBBBB

BBBBB BBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBB

BBBBB BBBBB
    XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        BBB BBBB BB BBBBBBBBBBBBBBBBB  
            XXXXXXXXX XXXXXXXXXX
        BBBBBB
    XXXXXXXX
BBBBBBBB BBBBB